
Navigation Menu

Code
Pull requests
Actions
Editing app.json in KERM_MD-V4
Unsaved changes
You have unsaved changes on this file that can be restored.
BreadcrumbsKERM_MD-V4
/
app.json
in
main

Edit

Preview
Indent mode

Spaces
Indent size

2
Line wrap mode

No wrap
Editing app.json file contents
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
    "AUTO_REPLY": {

    "AUTO_READ_STATUS": {
      "description": "Make it true if you want bot auto auto_read_status.",
      "required": true,
      "value": "true"
    }, 

    "ANTI_LINK": {
      "description": "Make it true if you want bot auto remove group link.",
      "required": true,
      "value": "true"
    },

    "ANTI_BAD": {
      "description": "Make it true if you want bot auto delete bad words from group example xxx porn etc.",
      "required": true,
      "value": "false"
    }, 

    "FAKE_RECORDING": {
      "description": "Make it true if you want bot fake record.",
      "required": true,
      "value": "true"
    },

    "AUTO_REACT": {
      "description": "Make it true if you want bot AutoReact.",
      "required": false,
      "value": "false"
    },

    "OWNER_REACT": {
      "description": "Make it true if you want bot OwnerReact.",
      "required": false,
      "value": "false"
    
    }, 

    "BOT_NAME": {
      "description": "write hear your name.",
      "required": true,
      "value": "âœ¦ã€ğ—ğ—˜ğ—¥ğ—  ğ— ğ—— ğ—©4ã€âœ¦"
    }, 

    "HEART_REACT": {
      "description": "Make it true if you want bot only heart â™¥ï¸ emjois reaction .",
      "required": true,
      "value": "false"
    }

},

     "buildpacks": [
        {
            "url": "https://github.com/heroku/heroku-buildpack-nodejs.git"
        }
     ],
  "stack": "heroku-24"
